const SHA256 = require('crypto-js/sha256');

class Block{
    constructor(index, timestamp, data, previousHash = ''){

        this.index = index;                 // This is the index number for the no. of Blocks
        this.timestamp = timestamp;         // This is to store the time data in the block
        this.data = data;                   // This is the actual data/transaction data we want to block
        this.previousHash = previousHash;   // This is to store the Hash of the previous Block
        this.hash = this.calculateHash();   // This is to calculate and store the Current Block's Hash
        this.nonce = 0;                     // This is used for Proof-Of-Work. This value will be used to create different Hash for same block until it serves Proof-Of-Work
    }

    // Function to calculate new has for the Current Block
    calculateHash()
    {
        //The hash is done using the index, timestamp, data, previoushHash and the nonce.
        return SHA256(this.index + this.previousHash + this.timestamp + JSON.stringify(this.data) + this.nonce).toString();
    }

    //This function is used to increase the difficulty(Proof-Of-Work). Until the specified condition is met, the hash is re-generated by incrementing the Nonce value
    mineBlock(difficulty){

        while(this.hash.substring(0,difficulty) !== Array(difficulty + 1).join("0")){
            this.nonce++;
            this.hash = this.calculateHash();
        }

        console.log("Block mined: " + this.hash);
}

}

class Blockchain{
    constructor(){
        this.chain = [this.createGenesisBlock()];
        this.difficulty = 4;

    }

    createGenesisBlock(){
        return new Block(0, "01/01/2018","Genesis block","0");
    }


    getLatestBlock(){
        return this.chain[this.chain.length - 1];
    }

    addBlock(newBlock){
        newBlock.previousHash = this.getLatestBlock().hash;
        newBlock.mineBlock(this.difficulty);
        this.chain.push(newBlock);

    }
}

let creditLoft = new Blockchain();
console.log("Mining Block 1...");
creditLoft.addBlock(new Block(1,"10/07/2017", {amount:4}));

console.log("Mining Block 2...");

creditLoft.addBlock(new Block(2,"12/07/2017", {amount:10}));

console.log(JSON.stringify(creditLoft, null, 4));
